[data]
; ── 训练集 ──────────────────────────────────────────────────
train_meta   = /public/home/zixuan_li/myproject/ACANN_mainv3/traindata/torch_data_delta0.3_2/A_training_meta.npz
train_nc     =/public/home/zixuan_li/myproject/ACANN_mainv3/traindata/torch_data_delta0.3_2/nl_training_0.0.csv
nb_train     = 45000

; ── 验证集（同一文件自动切分）──────────────────────────────
val_meta     = /public/home/zixuan_li/myproject/ACANN_mainv3/traindata/torch_data_delta0.3_2/A_training_meta.npz
val_nc       = /public/home/zixuan_li/myproject/ACANN_mainv3/traindata/torch_data_delta0.3_2/nl_training_0.0.csv
nb_val       = 5000


; ── 训练分辨率 ──────────────────────────────────────────────
train_w1     = 500
train_w2     = 500

[model]
nb_gc        =128
n_peaks      = 3

; ── 残差 MLP 编码器 ─────────────────────────────────────────
d_hidden     = 512
n_layers     = 6
dropout      = 0.05

[optim]
optimizer    = adamw
lr           = 1.5e-4
lr_min       = 1e-6
weight_decay = 0.01
grad_clip    = 1.0

warmup_epochs = 5
epochs        = 200

batch_size   = 512
num_workers  = 8

amp          = true
ema          = true
ema_decay    = 0.999

[loss]
mse_w        = 1.0
l1_w         = 0.5
gate_w       = 0.02

[output]
ckpt_dir     = checkpoints_2.2
plot_dir     = plots_2.2
print_every  = 50
val_every    = 200
